title: Malia Barker
description: Computer Scientist, Data Scientist, and Astrophysics Enthusiast
site_title: '@maliabarker - Malia Barker'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: maliabarker
blog_url: https://www.maliabarker.com
email: maliabarker@icloud.com

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
# google_analytics: 